In [242]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

##storing Total Dataset which has been sampled and cleaned into one dataframe
data = pd.read_csv("TotalData_Cleaned_Sampled.csv")
df = pd.DataFrame(data)
#creating one dataframe to store outliers
dfi = pd.DataFrame()
#Keeping track of standard deviation and mean for both speed and signal strength values
x1 = df['speed'].std()
y1 = df['speed'].mean()
x2 = df['signal_strength'].std()
y2 = df['signal_strength'].mean()
df

,service_provider,technology,download/upload,speed,signal_strength,state,Month,Year
0,JIO,4G,download,8181,-77.000000,Gujarat,July,2018
1,JIO,4G,download,121,-101.000000,Gujarat,July,2018
2,JIO,4G,download,3579,-88.000000,Gujarat,July,2018
3,JIO,4G,download,23052,-72.000000,Gujarat,July,2018
4,JIO,4G,download,8654,-77.230348,Gujarat,July,2018
...,...,...,...,...,...,...,...,...
342776,VODAFONE,3G,upload,82,-99.000000,North East,March,2019
342777,VODAFONE,3G,upload,108,-101.000000,North East,March,2019
342778,VODAFONE,3G,upload,193,-63.000000,North East,March,2019
342779,VODAFONE,3G,upload,97,-99.000000,North East,March,2019
342780,VODAFONE,3G,upload,2131,-81.000000,North East,March,2019

In [243]:
#applying z score normalization
df['signal_strength']=(df['signal_strength']-df['signal_strength'].mean())/df['signal_strength'].std()
df['speed']=(df['speed']-df['speed'].mean())/df['speed'].std()
df

,service_provider,technology,download/upload,speed,signal_strength,state,Month,Year
0,JIO,4G,download,-0.114966,0.683837,Gujarat,July,2018
1,JIO,4G,download,-0.623736,-0.912410,Gujarat,July,2018
2,JIO,4G,download,-0.405457,-0.047776,Gujarat,July,2018
3,JIO,4G,download,0.823734,1.016389,Gujarat,July,2018
4,JIO,4G,download,-0.085108,0.668517,Gujarat,July,2018
...,...,...,...,...,...,...,...,...
342776,VODAFONE,3G,upload,-0.626197,-0.779389,North East,March,2019
342777,VODAFONE,3G,upload,-0.624556,-0.912410,North East,March,2019
342778,VODAFONE,3G,upload,-0.619191,1.614982,North East,March,2019
342779,VODAFONE,3G,upload,-0.625250,-0.779389,North East,March,2019
342780,VODAFONE,3G,upload,-0.496859,0.417796,North East,March,2019

In [244]:
#Tested all the outlier thresholds to find that only outliers exist with z score values greater than 3 for speed 
#so storing them in dfi
dfi = dfi.append(df.loc[df['speed'] > 3]).copy()
dfi

,service_provider,technology,download/upload,speed,signal_strength,state,Month,Year
17,JIO,4G,download,3.310079,1.481961,Gujarat,July,2018
31,JIO,4G,download,4.107320,1.681492,Gujarat,July,2018
44,JIO,4G,download,4.237984,1.415451,Gujarat,July,2018
63,JIO,4G,download,4.441176,1.614982,Gujarat,July,2018
67,JIO,4G,download,4.054675,1.881023,Gujarat,July,2018
...,...,...,...,...,...,...,...,...
340972,JIO,4G,download,3.510999,2.346595,Bihar,March,2019
340983,JIO,4G,download,3.616224,2.346595,Bihar,March,2019
340987,JIO,4G,download,3.257245,2.346595,Bihar,March,2019
341676,JIO,4G,download,5.085534,0.218265,Assam,March,2019
342179,AIRTEL,4G,download,3.181371,0.949879,North East,March,2019

In [245]:
#Removing all outliers
df = df.loc[df['speed'] <= 3].copy()
df

,service_provider,technology,download/upload,speed,signal_strength,state,Month,Year
0,JIO,4G,download,-0.114966,0.683837,Gujarat,July,2018
1,JIO,4G,download,-0.623736,-0.912410,Gujarat,July,2018
2,JIO,4G,download,-0.405457,-0.047776,Gujarat,July,2018
3,JIO,4G,download,0.823734,1.016389,Gujarat,July,2018
4,JIO,4G,download,-0.085108,0.668517,Gujarat,July,2018
...,...,...,...,...,...,...,...,...
342776,VODAFONE,3G,upload,-0.626197,-0.779389,North East,March,2019
342777,VODAFONE,3G,upload,-0.624556,-0.912410,North East,March,2019
342778,VODAFONE,3G,upload,-0.619191,1.614982,North East,March,2019
342779,VODAFONE,3G,upload,-0.625250,-0.779389,North East,March,2019
342780,VODAFONE,3G,upload,-0.496859,0.417796,North East,March,2019

In [246]:
#converting normalized values back to real values in outlier dataframe
dfi['speed']=dfi['speed']*x1+y1
dfi['signal_strength']=dfi['signal_strength']*x2+y2
dfi

,service_provider,technology,download/upload,speed,signal_strength,state,Month,Year
17,JIO,4G,download,62441.0,-65.0,Gujarat,July,2018
31,JIO,4G,download,75071.0,-62.0,Gujarat,July,2018
44,JIO,4G,download,77141.0,-66.0,Gujarat,July,2018
63,JIO,4G,download,80360.0,-63.0,Gujarat,July,2018
67,JIO,4G,download,74237.0,-59.0,Gujarat,July,2018
...,...,...,...,...,...,...,...,...
340972,JIO,4G,download,65624.0,-52.0,Bihar,March,2019
340983,JIO,4G,download,67291.0,-52.0,Bihar,March,2019
340987,JIO,4G,download,61604.0,-52.0,Bihar,March,2019
341676,JIO,4G,download,90568.0,-84.0,Assam,March,2019
342179,AIRTEL,4G,download,60402.0,-73.0,North East,March,2019

In [247]:
#converting normalized values back to real values in main dataframe which has no outliers
df['speed']=df['speed']*x1+y1
df['signal_strength']=df['signal_strength']*x2+y2
df

,service_provider,technology,download/upload,speed,signal_strength,state,Month,Year
0,JIO,4G,download,8181.0,-77.000000,Gujarat,July,2018
1,JIO,4G,download,121.0,-101.000000,Gujarat,July,2018
2,JIO,4G,download,3579.0,-88.000000,Gujarat,July,2018
3,JIO,4G,download,23052.0,-72.000000,Gujarat,July,2018
4,JIO,4G,download,8654.0,-77.230348,Gujarat,July,2018
...,...,...,...,...,...,...,...,...
342776,VODAFONE,3G,upload,82.0,-99.000000,North East,March,2019
342777,VODAFONE,3G,upload,108.0,-101.000000,North East,March,2019
342778,VODAFONE,3G,upload,193.0,-63.000000,North East,March,2019
342779,VODAFONE,3G,upload,97.0,-99.000000,North East,March,2019
342780,VODAFONE,3G,upload,2131.0,-81.000000,North East,March,2019

In [248]:
#exporting outlier dataset
dfi.to_csv("outliers.csv", index=False)

In [249]:
#exporting main dataframe
df.to_csv("TotalData_Cleaned_Sampled_OutliersRemoved.csv", index=False)